### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by scottwhudson** [huesorg/uncopyright#16]
I'm starting to look at implementing the user model and authentication. 

Since the general goal is to make this project as accessible as possible, I assume we'll only authenticate when a user wants to create, edit, or delete project posts.  All other views will be usable to anyone that visits the site.  

I'm looking at the [Passport.js](http://passportjs.org/) module to use, which supports several different auth strategies like 3rd-party OAuth and hashing.  

Going the hashing route would be the most basic and most accessible since not everyone has a facebook account, but it does mean we'd need to store hashed passwords in our database.

What are your thoughts?

**Comment by killermann** [comment]
I think that's fine, if it's something you think we need. For MVP version, I figured we were going to leave out user auth and just manage the database entries through mongo gui, but this sounds more hands off.

P.S. That passport.js site UI/X has me 😍 especially the strategies page and search. Damn.

**Comment by killermann** [comment]
> I assume we'll only authenticate when a user wants to create, edit, or delete project posts. All other views will be usable to anyone that visits the site.

Agreed on this 100
