### ISSUE TITLE
Infinite Scroll on project page

### ISSUE THREAD

**Issue by scottwhudson** [huesorg/uncopyright#17]
It appears that because we're rendering everything on the server, the only way to get functionality like this is to implement paging.  I know it's not as sexy, but it should be pretty quick to set up. Does that work for you, at least for the MVP version of this?

**Comment by killermann** [comment]
Totally works. I was reading some React documentation last night to get a better handle on the server-side vs browser-side rendering, but I think I'm still at 1% understanding.

Can you build that?

**Comment by scottwhudson** [comment]
Aye aye 👍
